string poses_text
sensor_msgs/Image image
---
float64 response_linearx1
float64 response_angularz1
float64 response_linearx2
float64 response_angularz2
float64 response_linearx3
float64 response_angularz3

